fail_fast: true
repos:
  - repo: local
    hooks:
      - id: system
        name: Black
        entry: black .
        pass_filenames: false
        language: system
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort .
        pass_filenames: false
        language: system
  - repo: local
    hooks:
      - id: system
        name: MyPy
        entry: mypy .
        pass_filenames: false
        language: system
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.35.0
    hooks:
    - id: markdownlint
