version: "3.9"
services:
  product_db:
    image: postgres:15-alpine
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - ${PWD}/config/.env
    healthcheck:
      test: pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}
      timeout: 5s
      interval: 30s
      retries: 3
    networks:
      - back-tier

  product_api:
    image: product_api:latest
    restart: unless-stopped
    env_file:
      - ${PWD}/config/.env
    depends_on:
      - product_db
    networks:
      - back-tier
    ports:
      - 8000:8000

volumes:
  pgdata:

networks:
  back-tier:
    external: true
